name: CI on Merge

on:
  push:
    branches:
      - mainline

env:
  VERSION: "2.${GITHUB_RUN_NUMBER}.0"

jobs:
  Git_Tag:
    runs-on: ubuntu-latest
    name: Create and update new git tag test
    steps:
      - name: Checkout code-base code
        uses: actions/checkout@v2

      - name: Git Tag
        id: new-code-base-tag
        run: |
          tag=${{ env.version }}
          echo "Tag: $tag"
          git tag $tag
          git push --tags

      - name: Git Tag Source repo
        id: new-source-base-tag
        run: |
          git clone https://x-access-token:${{ secrets.SECOND_REPO_PAT }}@github.com/tu-anh-nguyen/source_repo.git
          cd source_repo
          git remote -v
          git checkout ${{ steps.determine-source-branch-ref.outputs.branch_ref }}
          tag=${{ env.version }}
          echo "Tag: $tag"
          git tag $tag
          git push origin $tag
